services:
  web:
    build: ./Library_GITY/
    command: gunicorn Library_system.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    volumes:
      - ./gity_db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
